// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKXcJV7SK2eq0C2KtqqlnqejMEdWZEIFY',
    appId: '1:473106444167:android:0f4222fe5097f416212d22',
    messagingSenderId: '473106444167',
    projectId: 'fruit-hub-d698f',
    storageBucket: 'fruit-hub-d698f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDccNMgaecrAnMFnoiIn2maV0T0eI351KI',
    appId: '1:473106444167:ios:8456f503935f7204212d22',
    messagingSenderId: '473106444167',
    projectId: 'fruit-hub-d698f',
    storageBucket: 'fruit-hub-d698f.firebasestorage.app',
    androidClientId: '473106444167-kr53rsreb16qonknhgmpaeufcf0c159k.apps.googleusercontent.com',
    iosClientId: '473106444167-dgo5tl39klvj5melkkuh1p54ie2ueva7.apps.googleusercontent.com',
    iosBundleId: 'com.ismail.fruitsHubDashboard',
  );
}
